# Generated by Django 5.1.5 on 2025-03-16 15:14

import case_studies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Check to publish. Unpublished page doesnt appear in the navigation, but can still be previewed under its URL ([slug] or [parent_slug/slug])', verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu_title', models.CharField(help_text='Page title as displayed in page header and breadcrumbs, max 60 characters', max_length=60, verbose_name='Title')),
                ('slug', models.SlugField(help_text='URL is created automatically based on menu title. Dont touch unless title is long and not suitable for url', unique=True, verbose_name='URL Settings')),
                ('thumbnail', models.ImageField(blank=True, help_text='1:1 ratio, 300px x 300px', null=True, upload_to=case_studies.models.upload_to)),
                ('meta_title', models.CharField(blank=True, help_text='Title displayed in browser tab and search results. Auto-filled from menu title', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ('order',),
            },
        ),
    ]
