# Generated by Django 5.1.5 on 2025-03-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0001_initial'),
        ('experts', '0003_expert_thumbnail_alter_expert_name_alter_expert_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Chose an expert to display at the bottom of the page (no selection = no expert)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expert'),
        ),
    ]
