# Generated by Django 5.1.5 on 2025-03-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0002_casestudy_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Year as displayed in index thumbnail caption. Also used for sorting the list', null=True),
        ),
    ]
