# Generated by Django 5.1.5 on 2025-03-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0003_casestudy_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ('-year',), 'verbose_name': 'Case Study', 'verbose_name_plural': 'Case Studies'},
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='order',
        ),
    ]
