# Generated by Django 5.1.5 on 2025-03-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0004_alter_casestudy_options_remove_casestudy_order'),
        ('covers', '0004_alter_cover_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='Chose case study cover (no selection = no cover)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='covers.casestudycover'),
        ),
    ]
