# Generated by Django 5.1.5 on 2025-03-31 12:57

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0005_casestudy_cover'),
        ('labels', '0003_alter_label_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='header',
            field=models.CharField(blank=True, help_text='Header of Key Data block', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='labels_header',
            field=models.CharField(blank=True, help_text='Header of labels group', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CaseStudyLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.ForeignKey(blank=True, help_text='Choose or create a new label. Labels are reusable accross the page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.label')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='case_studies.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Label',
                'verbose_name_plural': 'Case Study Labels',
                'ordering': ('order',),
            },
        ),
    ]
