# Generated by Django 5.1.5 on 2025-03-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0006_casestudy_header_casestudy_labels_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(help_text='Displayed in the first column of Key Data table', max_length=60)),
                ('data_content', models.CharField(help_text='Displayed in the second column of Key Data table', max_length=255, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_items', to='case_studies.casestudy')),
            ],
            options={
                'verbose_name': 'Data Item',
                'verbose_name_plural': 'Data Items',
                'ordering': ('order',),
            },
        ),
    ]
