# Generated by Django 5.1.5 on 2025-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0007_casestudydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudydata',
            name='data_content',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_type',
            field=models.CharField(blank=True, help_text='Displayed in the first column of Key Data table', max_length=60, null=True),
        ),
    ]
