# Generated by Django 5.1.5 on 2025-03-31 16:37

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0008_alter_casestudydata_data_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudydata',
            name='data_content',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, help_text='Displayed in the first column of Key Data table', max_length=120, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='case_studies.casestudy')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ('order',),
            },
        ),
    ]
