# Generated by Django 5.1.5 on 2025-03-31 17:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0010_rename_page_section_case_study_alter_section_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='header',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=tinymce.models.HTMLField(blank=True, help_text='Optional text to display below section images. Format with break-lines.', null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional caption to display below an image. Format with break-lines', max_length=500, null=True),
        ),
    ]
