# Generated by Django 5.1.5 on 2025-03-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0011_alter_section_header_alter_section_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional caption to display below an image. Format with break-lines.', max_length=500, null=True),
        ),
    ]
