# Generated by Django 5.1.5 on 2025-03-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0012_alter_sectionimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional caption to display below an image.', max_length=500, null=True),
        ),
    ]
