# Generated by Django 5.1.5 on 2025-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0013_alter_sectionimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='index_cover_slider',
            field=models.BooleanField(default=True, help_text='Check to display Cover in header slider on Case Study Index Page', verbose_name='Show in Index slider'),
        ),
    ]
