# Generated by Django 5.1.5 on 2025-04-02 18:11

import case_studies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0016_alter_sectionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check to publish. Unpublished Case Study doesnt appear in Case Study Index page, but can still be previewed under its URL (example: /company/case-studies/zeekr-x/).', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='menu_title',
            field=models.CharField(help_text='Case Study title as displayed in page header and breadcrumbs, max 60 characters', max_length=60, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(help_text='URL is created automatically based on title. Dont touch unless title is long and not suitable for url', unique=True, verbose_name='URL Settings'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='3:2 ratio, 1280px x 854px', null=True, upload_to=case_studies.models.upload_to),
        ),
        migrations.AlterField(
            model_name='section',
            name='header',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines. If both Header and Text fields are left empty, images will flow continuously to next section.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Image order within the the block'),
        ),
    ]
