# Generated by Django 5.1.5 on 2025-04-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0017_alter_casestudy_is_published_and_more'),
        ('experts', '0005_alter_expert_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Chose or add an expert to display at the bottom of the page (no selection = no expert)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expert'),
        ),
    ]
