# Generated by Django 5.1.5 on 2025-04-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0018_alter_casestudy_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional caption to display below an image (max 255 characters)', max_length=255, null=True),
        ),
    ]
