# Generated by Django 5.1.5 on 2025-04-05 17:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0020_alter_casestudydata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='header_de',
            field=models.CharField(blank=True, default='Key data:', help_text='Header of Key Data block', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='header_en',
            field=models.CharField(blank=True, default='Key data:', help_text='Header of Key Data block', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='header_pl',
            field=models.CharField(blank=True, default='Key data:', help_text='Header of Key Data block', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='labels_header_de',
            field=models.CharField(blank=True, default='Scope of work:', help_text='Header of labels group', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='labels_header_en',
            field=models.CharField(blank=True, default='Scope of work:', help_text='Header of labels group', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='labels_header_pl',
            field=models.CharField(blank=True, default='Scope of work:', help_text='Header of labels group', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='menu_title_de',
            field=models.CharField(help_text='Case Study title as displayed in page header and breadcrumbs, max 60 characters', max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='menu_title_en',
            field=models.CharField(help_text='Case Study title as displayed in page header and breadcrumbs, max 60 characters', max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='menu_title_pl',
            field=models.CharField(help_text='Case Study title as displayed in page header and breadcrumbs, max 60 characters', max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_title_de',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_title_pl',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='text_de',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='text_pl',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudydata',
            name='data_content_de',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casestudydata',
            name='data_content_en',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casestudydata',
            name='data_content_pl',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casestudydata',
            name='data_type_de',
            field=models.CharField(blank=True, help_text='( Year / Client / Team / Tools ) Displayed in the first column of Key Data table', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudydata',
            name='data_type_en',
            field=models.CharField(blank=True, help_text='( Year / Client / Team / Tools ) Displayed in the first column of Key Data table', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='casestudydata',
            name='data_type_pl',
            field=models.CharField(blank=True, help_text='( Year / Client / Team / Tools ) Displayed in the first column of Key Data table', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='header_de',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines. If both Header and Text fields are left empty, images will flow continuously to next section.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='header_en',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines. If both Header and Text fields are left empty, images will flow continuously to next section.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='header_pl',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines. If both Header and Text fields are left empty, images will flow continuously to next section.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text_de',
            field=tinymce.models.HTMLField(blank=True, help_text='Optional text to display below section images. Format with break-lines.', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Optional text to display below section images. Format with break-lines.', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text_pl',
            field=tinymce.models.HTMLField(blank=True, help_text='Optional text to display below section images. Format with break-lines.', null=True),
        ),
        migrations.AddField(
            model_name='sectionimage',
            name='caption_de',
            field=models.TextField(blank=True, help_text='Optional caption to display below an image (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionimage',
            name='caption_en',
            field=models.TextField(blank=True, help_text='Optional caption to display below an image (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionimage',
            name='caption_pl',
            field=models.TextField(blank=True, help_text='Optional caption to display below an image (max 255 characters)', max_length=255, null=True),
        ),
    ]
