# Generated by Django 5.1.5 on 2025-04-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0021_casestudy_header_de_casestudy_header_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption to display below an image (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='caption_de',
            field=models.CharField(blank=True, help_text='Optional caption to display below an image (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='caption_en',
            field=models.CharField(blank=True, help_text='Optional caption to display below an image (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='caption_pl',
            field=models.CharField(blank=True, help_text='Optional caption to display below an image (max 255 characters)', max_length=255, null=True),
        ),
    ]
