# Generated by Django 5.1.5 on 2025-04-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0022_alter_sectionimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='header',
            field=models.CharField(blank=True, help_text='Header of Key Data block', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='header_de',
            field=models.CharField(blank=True, help_text='Header of Key Data block', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='header_en',
            field=models.CharField(blank=True, help_text='Header of Key Data block', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='header_pl',
            field=models.CharField(blank=True, help_text='Header of Key Data block', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='labels_header',
            field=models.CharField(blank=True, help_text='Header of labels group', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='labels_header_de',
            field=models.CharField(blank=True, help_text='Header of labels group', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='labels_header_en',
            field=models.CharField(blank=True, help_text='Header of labels group', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='labels_header_pl',
            field=models.CharField(blank=True, help_text='Header of labels group', max_length=60, null=True),
        ),
    ]
