# Generated by Django 5.1.5 on 2025-05-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0024_alter_casestudy_menu_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='header',
            field=models.CharField(blank=True, help_text='Header of Key Data block, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='header_de',
            field=models.CharField(blank=True, help_text='Header of Key Data block, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='header_en',
            field=models.CharField(blank=True, help_text='Header of Key Data block, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='header_pl',
            field=models.CharField(blank=True, help_text='Header of Key Data block, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='labels_header',
            field=models.CharField(blank=True, help_text='Header of labels group, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='labels_header_de',
            field=models.CharField(blank=True, help_text='Header of labels group, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='labels_header_en',
            field=models.CharField(blank=True, help_text='Header of labels group, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='labels_header_pl',
            field=models.CharField(blank=True, help_text='Header of labels group, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_title_de',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_title_pl',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(help_text='URL is created automatically based on title. Dont touch unless title is long and not suitable for url. Must be unique. Max 50 characters', unique=True, verbose_name='URL Settings'),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_content',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_content_de',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_content_en',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_content_pl',
            field=models.CharField(blank=True, help_text='Displayed in the second column of Key Data table, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_type',
            field=models.CharField(blank=True, help_text='( Year / Client / Team / Tools ) Displayed in the first column of Key Data table, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_type_de',
            field=models.CharField(blank=True, help_text='( Year / Client / Team / Tools ) Displayed in the first column of Key Data table, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_type_en',
            field=models.CharField(blank=True, help_text='( Year / Client / Team / Tools ) Displayed in the first column of Key Data table, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='casestudydata',
            name='data_type_pl',
            field=models.CharField(blank=True, help_text='( Year / Client / Team / Tools ) Displayed in the first column of Key Data table, max 60 characters', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='header',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines. If both Header and Text fields are left empty, images will flow continuously to next section. Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='header_de',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines. If both Header and Text fields are left empty, images will flow continuously to next section. Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='header_en',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines. If both Header and Text fields are left empty, images will flow continuously to next section. Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='header_pl',
            field=models.TextField(blank=True, help_text='Optional Header to display below section images. Format with break-lines. If both Header and Text fields are left empty, images will flow continuously to next section. Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption to display below an image, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='caption_de',
            field=models.CharField(blank=True, help_text='Optional caption to display below an image, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='caption_en',
            field=models.CharField(blank=True, help_text='Optional caption to display below an image, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='caption_pl',
            field=models.CharField(blank=True, help_text='Optional caption to display below an image, max 255 characters', max_length=255, null=True),
        ),
    ]
