# Generated by Django 5.1.5 on 2025-05-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0025_alter_casestudy_header_alter_casestudy_header_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='menu_title',
            field=models.CharField(help_text='Case Study title as displayed in page header and breadcrumbs. Must be unique, max 60 characters', max_length=60, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='menu_title_de',
            field=models.CharField(help_text='Case Study title as displayed in page header and breadcrumbs. Must be unique, max 60 characters', max_length=60, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='menu_title_en',
            field=models.CharField(help_text='Case Study title as displayed in page header and breadcrumbs. Must be unique, max 60 characters', max_length=60, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='menu_title_pl',
            field=models.CharField(help_text='Case Study title as displayed in page header and breadcrumbs. Must be unique, max 60 characters', max_length=60, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(help_text='URL is created automatically based on title. Dont touch unless title is long and not suitable for url. Must be unique, max 50 characters', unique=True, verbose_name='URL Settings'),
        ),
    ]
