# Generated by Django 5.1.5 on 2025-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0026_alter_casestudy_menu_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
    ]
