# Generated by Django 5.1.5 on 2025-03-12 20:40

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_homepage', models.BooleanField(default=False, help_text='Select as Home Page', verbose_name='Home Page')),
                ('is_section_1_parent', models.BooleanField(default=False, help_text='Select a single section 1 parent page', verbose_name='Section 1 Parent')),
                ('is_section_2_parent', models.BooleanField(default=False, help_text='Select a single section 2 parent page', verbose_name='Section 2 Parent')),
                ('published', models.BooleanField(default=False, help_text='Check to publish. Unpublished page doesnt appear in the navigation and search results, but can still be previewed under its URL ([slug] or [parent_slug/slug])', verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(help_text='URL is created automatically based on menu title. Dont touch unless title is long and not suitable for url', unique=True, verbose_name='URL Settings')),
                ('menu_title', models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60)),
                ('footer_title', models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True)),
                ('title', models.CharField(help_text='Page title as displayed in page header, max 60 characters', max_length=60)),
                ('thumbnail', models.ImageField(blank=True, help_text='1:1 ratio, 300px x 300px', null=True, upload_to=pages.models.upload_to)),
                ('meta_title', models.CharField(blank=True, help_text='Title displayed in browser tab and search results. Auto-filled from menu title', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True)),
                ('cover', models.ManyToManyField(related_name='page', to='covers.cover')),
                ('parent', models.ForeignKey(blank=True, help_text='Chose parent page (chose if page belongs to section 1 or 2)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page')),
            ],
            options={
                'verbose_name': 'General Page',
                'verbose_name_plural': 'General Pages',
                'unique_together': {('parent', 'slug')},
            },
        ),
    ]
