# Generated by Django 5.1.5 on 2025-03-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60),
        ),
    ]
