# Generated by Django 5.1.5 on 2025-03-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='published',
            new_name='is_published',
        ),
    ]
