# Generated by Django 5.1.5 on 2025-03-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0001_initial'),
        ('pages', '0003_rename_published_page_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_homepage',
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Check to publish. Unpublished page doesnt appear in the navigation and search results, but can still be previewed under its URL ([slug] or [parent_slug/slug])', verbose_name='Published')),
                ('title', models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60)),
                ('meta_title', models.CharField(blank=True, help_text='Title displayed in browser tab and search results. Auto-filled from menu title', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True)),
                ('cover', models.ManyToManyField(related_name='home_page', to='covers.cover')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
    ]
