# Generated by Django 5.1.5 on 2025-03-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_page_is_homepage_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='is_published',
        ),
    ]
