# Generated by Django 5.1.5 on 2025-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_homepage_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60)),
                ('meta_title', models.CharField(blank=True, help_text='Title displayed in browser tab and search results. Auto-filled from menu title', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
