# Generated by Django 5.1.5 on 2025-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='footer_title',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='menu_title',
            field=models.CharField(default='Contact', help_text='Page title as displayed in page menu, max 60 characters', max_length=60),
            preserve_default=False,
        ),
    ]
