# Generated by Django 5.1.5 on 2025-03-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contact_footer_title_contact_menu_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageNotFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='404 message text', null=True)),
                ('link_text', models.TextField(blank=True, help_text='404 link text', null=True)),
            ],
            options={
                'verbose_name': '404 Page',
                'verbose_name_plural': '404 Page',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL is created automatically based on menu title. Dont touch unless title is long and not suitable for url', unique=True, verbose_name='URL Settings')),
                ('menu_title', models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60)),
                ('footer_title', models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True)),
                ('title', models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60)),
                ('text', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Title displayed in browser tab and search results. Auto-filled from menu title', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('order',), 'verbose_name': 'General Page', 'verbose_name_plural': 'General Pages'},
        ),
        migrations.CreateModel(
            name='PrivacyPolicyButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, help_text='button URL', max_length=255, null=True, verbose_name='Button URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.privacypolicy', verbose_name='Performance')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'ordering': ('order',),
            },
        ),
    ]
