# Generated by Django 5.1.5 on 2025-03-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_pagenotfound_privacypolicy_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagenotfound',
            name='link_text',
            field=models.CharField(blank=True, help_text='404 link text', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagenotfound',
            name='text',
            field=models.CharField(blank=True, help_text='404 message text', max_length=255, null=True),
        ),
    ]
