# Generated by Django 5.1.5 on 2025-03-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_pagenotfound_link_text_alter_pagenotfound_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_case_studies_index',
            field=models.BooleanField(default=False, help_text='Select a single Case Studies Index page', verbose_name='Case Studies Index'),
        ),
    ]
