# Generated by Django 5.1.5 on 2025-03-15 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_page_is_case_studies_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, help_text='Address as displayed in header. Format text with break-lines'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_footer',
            field=models.TextField(blank=True, help_text='Address as displayed in footer. Format text with break-lines'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, help_text='Email address in proper format', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='fiscal_data',
            field=models.TextField(blank=True, help_text='VAT ID / REGON / KRS as displayed in header. Format text with break-lines'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in proper format', max_length=50),
        ),
        migrations.AlterField(
            model_name='privacypolicybutton',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.privacypolicy', verbose_name='Privacy Policy Button'),
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(blank=True, help_text='Link text', max_length=60, null=True, verbose_name='Link text')),
                ('link_url', models.CharField(blank=True, help_text='Link URL', max_length=255, null=True, verbose_name='Link URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='First link is displayed in the header as a button')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.contact', verbose_name='Social Link')),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
                'ordering': ('order',),
            },
        ),
    ]
