# Generated by Django 5.1.5 on 2025-03-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_contact_address_contact_address_footer_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check to publish. Unpublished page doesnt appear in the navigation, but can still be previewed under its URL ([slug] or [parent_slug/slug])', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check to publish. Unpublished page doesnt appear in the navigation, but can still be previewed under its URL ([slug] or [parent_slug/slug])', verbose_name='Published'),
        ),
    ]
