# Generated by Django 5.1.5 on 2025-03-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_privacypolicy_is_published_alter_page_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='slug',
        ),
    ]
