# Generated by Django 5.1.5 on 2025-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_privacypolicy_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='button_1_text',
            field=models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_1_url',
            field=models.CharField(blank=True, help_text='button URL', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_2_text',
            field=models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_2_url',
            field=models.CharField(blank=True, help_text='button URL', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AddField(
            model_name='page',
            name='has_section_pages_list',
            field=models.BooleanField(default=False, help_text='Check to display thumbnails of pages as the first block below the header', verbose_name='Display section pages list'),
        ),
    ]
