# Generated by Django 5.1.5 on 2025-03-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_page_button_1_text_page_button_1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='thumbnail_caption',
            field=models.CharField(blank=True, default='Thumbnail caption for this page', help_text='Thumbnail caption as displayed in section pages list', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_1_text',
            field=models.CharField(blank=True, help_text='Button text (only applicable for section parents)', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_1_url',
            field=models.CharField(blank=True, help_text='button URL (only applicable for section parents)', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_2_text',
            field=models.CharField(blank=True, help_text='Button text (only applicable for section parents)', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_2_url',
            field=models.CharField(blank=True, help_text='button URL (only applicable for section parents)', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='has_section_pages_list',
            field=models.BooleanField(default=False, help_text='Check to display thumbnails of section pages as the first block below the header (only applicable for section parents)', verbose_name='Display section pages'),
        ),
    ]
