# Generated by Django 5.1.5 on 2025-03-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_page_thumbnail_caption_alter_page_button_1_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='button_1_text',
            field=models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_1_url',
            field=models.CharField(blank=True, help_text='Button URL. For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_2_text',
            field=models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_2_url',
            field=models.CharField(blank=True, help_text='Button URL. For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='privacypolicybutton',
            name='button_url',
            field=models.CharField(blank=True, help_text='Button URL. For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button URL'),
        ),
    ]
