# Generated by Django 5.1.5 on 2025-03-17 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expert_thumbnail_alter_expert_name_alter_expert_role'),
        ('pages', '0016_alter_page_button_1_text_alter_page_button_1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Chose an expert to display at the bottom of the page (no selection = no expert)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expert'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Chose parent page (chose if page belongs to section 1 or 2)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page'),
        ),
    ]
