# Generated by Django 5.1.5 on 2025-03-20 12:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_contact_expert_page_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
