# Generated by Django 5.1.5 on 2025-03-21 17:31

import django.db.models.deletion
import pages.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('labels', '0001_initial'),
        ('pages', '0019_alter_privacypolicy_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_footer',
            field=tinymce.models.HTMLField(blank=True, help_text='Address as displayed in footer. Format text with break-lines. For email link use mailto:email@g3.net.pl'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('full-width', 'Full-width'), ('timeline', 'Timeline')], default='left', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('header', models.TextField(blank=True, help_text='Block header, max 60 characters. Format text with break-lines.', max_length=80, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('button_1_text', models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button 1 text')),
                ('button_1_url', models.CharField(blank=True, help_text='Button URL. For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button 1 URL')),
                ('button_2_text', models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button 1 text')),
                ('button_2_url', models.CharField(blank=True, help_text='Button URL. For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button 1 URL')),
                ('append_scroll_nav', models.BooleanField(default=False, help_text='Check to append scroll navigation menu below the block', verbose_name='Append scroll nav')),
                ('append_clients', models.BooleanField(default=False, help_text='Check to append Clients list below the block', verbose_name='Append Clients list')),
                ('append_founders', models.BooleanField(default=False, help_text='Check to append Founders list below the block', verbose_name='Append Founders list')),
                ('append_team', models.BooleanField(default=False, help_text='Check to append Key Specialists list below the block', verbose_name='Append Key Specialists list')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('label', models.ForeignKey(blank=True, help_text='Choose or create a new label. Labels are reusable accross the page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.label')),
            ],
            options={
                'verbose_name': 'Content BLock',
                'verbose_name_plural': 'Content BLocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='JPG file, 3:2 ratio, 1500px x 1000px for blocks "Left", "Right" and "Timeline". For block "Full-width": 1920px x 1280px', null=True, upload_to=pages.models.upload_to)),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, help_text='Main image caption', max_length=120, null=True)),
                ('timeline_caption', models.TextField(blank=True, help_text='Long timeline block slider caption (leave blank for other block types)', max_length=255, null=True)),
                ('year', models.CharField(blank=True, help_text='Year / date header for timeline block slider. Format DD/MM/YYYY (leave blank for other block types)', max_length=10, null=True)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.contentblock')),
            ],
        ),
    ]
