# Generated by Django 5.1.5 on 2025-03-21 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0001_initial'),
        ('pages', '0021_remove_homepage_cover_homepage_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='cover',
        ),
        migrations.AddField(
            model_name='page',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='Chose page cover (no selection = no cover)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='covers.cover'),
        ),
    ]
