# Generated by Django 5.1.5 on 2025-03-21 22:34

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_page_cover_page_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='header',
            field=models.CharField(blank=True, help_text='Block header, max 80 characters.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contentblockimage',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG file, 3:2 ratio, 1500px x 1000px for blocks Left, Right and Timeline. For block Full-width: 1920px x 1280px', null=True, upload_to=pages.models.upload_to),
        ),
        migrations.AlterField(
            model_name='contentblockimage',
            name='timeline_caption',
            field=models.CharField(blank=True, help_text='Long timeline block slider caption (leave blank for other block types)', max_length=255, null=True),
        ),
    ]
