# Generated by Django 5.1.5 on 2025-03-22 18:46

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_contentblock_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='append_clients',
            field=models.BooleanField(default=False, help_text='Append Clients list below the block', verbose_name='Append Clients list'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='append_founders',
            field=models.BooleanField(default=False, help_text='Append Founders list below the block', verbose_name='Append Founders list'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='append_scroll_nav',
            field=models.BooleanField(default=False, help_text='Append scroll navigation menu below the block', verbose_name='Append scroll nav'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='append_team',
            field=models.BooleanField(default=False, help_text='Append Key Specialists list below the block', verbose_name='Append Key Specialists list'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='button_1_text',
            field=models.CharField(blank=True, help_text='Buttons are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='button_1_url',
            field=models.CharField(blank=True, help_text='For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='button_2_text',
            field=models.CharField(blank=True, help_text='Buttons are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='button_2_url',
            field=models.CharField(blank=True, help_text='For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button 2 URL'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='header',
            field=models.CharField(default='Block header', help_text='Block header, max 80 characters.', max_length=80),
        ),
        migrations.AlterField(
            model_name='contentblockimage',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG / PNG / GIF / ratio: 3:2 / width: 1280px (blocks Left, Right and Timeline) / width: 1680px (block Full-width)', null=True, upload_to=pages.models.upload_to),
        ),
        migrations.AlterField(
            model_name='contentblockimage',
            name='timeline_caption',
            field=models.CharField(blank=True, help_text='Long caption for timeline block (leave blank for other block types)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentblockimage',
            name='year',
            field=models.CharField(blank=True, help_text='Year / date for timeline block. Format DD/MM/YYYY (leave blank for other block types)', max_length=10, null=True),
        ),
    ]
