# Generated by Django 5.1.5 on 2025-03-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_contentblock_append_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='header',
            field=models.CharField(help_text='Block header (required), max 80 characters.', max_length=80),
        ),
    ]
