# Generated by Django 5.1.5 on 2025-03-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_contentblock_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['sort_order'], 'verbose_name': 'Content BLock', 'verbose_name_plural': 'Content BLocks'},
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='order',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
