# Generated by Django 5.1.5 on 2025-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_contentblock_options_remove_contentblock_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['order'], 'verbose_name': 'Content BLock', 'verbose_name_plural': 'Content BLocks'},
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
