# Generated by Django 5.1.5 on 2025-03-23 00:10

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_contentblock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblockimage',
            name='timeline_caption',
        ),
        migrations.RemoveField(
            model_name='contentblockimage',
            name='year',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='append_timeline',
            field=models.BooleanField(default=False, help_text='Append Timeline block below the block', verbose_name='Append Timeline block'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_clients_text',
            field=models.CharField(blank=True, help_text='Fill in if appending Clients list to this block', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_clients_url',
            field=models.CharField(blank=True, help_text='For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Clients button URL'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='display_type',
            field=models.CharField(choices=[('carousel', 'Carousel'), ('wipe', 'Wipe')], default='carousel', help_text='Choose display type for the images. If set to "wipe", the first two images will be used.', max_length=20, verbose_name='Image Display Type'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('full-width', 'Full-width')], default='left', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='button_1_text',
            field=models.CharField(blank=True, help_text='Buttons 1 and 2 are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='button_2_text',
            field=models.CharField(blank=True, help_text='Buttons 1 and 2 are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AlterField(
            model_name='contentblockimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Image caption', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contentblockimage',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG / PNG / GIF / ratio: 3:2 / width: 1280px (blocks Left, Right) / width: 1680px (block Full-width)', null=True, upload_to=pages.models.upload_to),
        ),
    ]
