# Generated by Django 5.1.5 on 2025-03-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_remove_contentblockimage_timeline_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='button_clients_text',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block', max_length=60, null=True, verbose_name='Clients button text'),
        ),
    ]
