# Generated by Django 5.1.5 on 2025-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_contentblock_new_tab_1_contentblock_new_tab_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='new_tab_1',
            field=models.BooleanField(default=False, verbose_name='Open in new tab'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='new_tab_2',
            field=models.BooleanField(default=False, verbose_name='Open in new tab'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='new_tab_clients',
            field=models.BooleanField(default=False, verbose_name='Open in new tab'),
        ),
    ]
