# Generated by Django 5.1.5 on 2025-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_contentblock_new_tab_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='block_id',
            field=models.SlugField(blank=True, help_text='For scroll navigation. ID is created automatically based on header', max_length=20, null=True, verbose_name='Block ID'),
        ),
    ]
