# Generated by Django 5.1.5 on 2025-03-24 12:02

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_contentblock_block_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='video',
            field=models.FileField(blank=True, help_text='Overrides Image Display Type: replaces carousel with a single video: mp4 file / recommended max size: 4Mb / length: ~30s', null=True, upload_to=pages.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_id',
            field=models.SlugField(blank=True, help_text='For scroll navigation. ID is created automatically based on header. Keep unique', max_length=20, null=True, verbose_name='Block ID'),
        ),
    ]
