# Generated by Django 5.1.5 on 2025-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_contentblock_video_alter_contentblock_block_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='video_caption',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contentblockimage',
            name='caption',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
