# Generated by Django 5.1.5 on 2025-03-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_alter_contentblock_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblockimage',
            name='caption',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
