# Generated by Django 5.1.5 on 2025-03-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_alter_contentblockimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='button_clients_text',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='button_clients_url',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='new_tab_clients',
        ),
    ]
