# Generated by Django 5.1.5 on 2025-03-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_remove_contentblock_button_clients_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblockimage',
            options={'ordering': ['order'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
