# Generated by Django 5.1.5 on 2025-03-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_alter_contentblockimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='video_caption',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
