# Generated by Django 5.1.5 on 2025-03-30 11:35

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_homepage_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblockimage',
            name='image',
            field=models.ImageField(default='/static/placeholder.jpg', help_text='WEBP / JPG / PNG / GIF / ratio: 3:2 / width: 1280px (blocks Left, Right) / width: 1680px (block Full-width)', upload_to=pages.models.upload_to),
        ),
    ]
