# Generated by Django 5.1.5 on 2025-03-30 11:37

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_alter_contentblockimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblockimage',
            name='image',
            field=models.ImageField(help_text='WEBP / JPG / PNG / GIF / ratio: 3:2 / width: 1280px (blocks Left, Right) / width: 1680px (block Full-width)', upload_to=pages.models.upload_to),
        ),
    ]
