# Generated by Django 5.1.5 on 2025-04-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_alter_contentblockimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='link_text',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Link text'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_1_text',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_1_url',
            field=models.CharField(blank=True, help_text='For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_2_text',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_2_url',
            field=models.CharField(blank=True, help_text='For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button 2 URL'),
        ),
    ]
