# Generated by Django 5.1.5 on 2025-04-02 18:11

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0004_alter_cover_options'),
        ('experts', '0005_alter_expert_role'),
        ('pages', '0045_alter_externallink_link_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Chose or add an expert to display at the bottom of the page (no selection = no expert)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expert'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='link_text',
            field=models.CharField(blank=True, help_text='First link is displayed in the header as a button', max_length=60, null=True, verbose_name='Link text'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='Chose or add page cover (no selection = no cover)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='covers.cover'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Chose or add an expert to display at the bottom of the page (no selection = no expert)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expert'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='Chose or add page cover (no selection = no cover)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='covers.cover'),
        ),
        migrations.AlterField(
            model_name='page',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Chose or add an expert to display at the bottom of the page (no selection = no expert)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.expert'),
        ),
        migrations.AlterField(
            model_name='page',
            name='has_section_pages_list',
            field=models.BooleanField(default=False, help_text='Check to display thumbnails of section pages as the first block below the header (only applicable for section Parent pages)', verbose_name='Display section pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check to publish. Unpublished page doesnt appear in the navigation, but can still be previewed under its URL (example: /company/ or /company/team/)', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines the order of subpages in menu and footer. N/A for parent pages (Can be left at "0")'),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='1:1 ratio, 300px x 300px. For display in desktop menu and Section Pages List. Can be left blank for Parent pages.', null=True, upload_to=pages.models.upload_to),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail_caption',
            field=models.CharField(blank=True, default='Thumbnail caption for this page', help_text='Thumbnail caption as displayed in Section Pages List. Can be left blank for Parent pages.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check to publish. Unpublished page doesnt appear in the navigation, but can still be previewed under its URL (example: /company/ or /company/team/)', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicybutton',
            name='button_text',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button text'),
        ),
    ]
