# Generated by Django 5.1.5 on 2025-04-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_alter_contact_expert_alter_contact_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['order'], 'verbose_name': 'Content Block', 'verbose_name_plural': 'Content Blocks'},
        ),
    ]
