# Generated by Django 5.1.5 on 2025-04-03 11:57

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_label_label_url_alter_label_label_text'),
        ('pages', '0047_alter_contentblock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='button_form_text',
            field=models.CharField(blank=True, default='Contact in a traditional way', help_text='Button scrolls to header section contact info', max_length=60, null=True, verbose_name='Contact Form button'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_form_label',
            field=models.ForeignKey(blank=True, help_text='Choose or create a new label. Labels are reusable accross the page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.label'),
        ),
        migrations.AddField(
            model_name='contact',
            name='form_header',
            field=models.CharField(blank=True, default='Drop us a line:', help_text='Max 80 characters.', max_length=80, null=True, verbose_name='Contact Form Header'),
        ),
        migrations.AddField(
            model_name='contact',
            name='form_text',
            field=tinymce.models.HTMLField(blank=True, help_text='Format with break-lines.', null=True, verbose_name='Contact Form Text'),
        ),
    ]
