# Generated by Django 5.1.5 on 2025-04-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_contact_button_form_text_contact_contact_form_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_form_label',
        ),
    ]
