# Generated by Django 5.1.5 on 2025-04-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_label_label_url_alter_label_label_text'),
        ('pages', '0049_remove_contact_contact_form_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='label',
            field=models.ForeignKey(blank=True, help_text='Choose or create a new label. Labels are reusable accross the page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.label'),
        ),
    ]
