# Generated by Django 5.1.5 on 2025-04-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_contact_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_de',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_pl',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_de',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_pl',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
    ]
