# Generated by Django 5.1.5 on 2025-04-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_homepage_meta_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='button_1_text_de',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_1_text_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_1_text_pl',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_2_text_de',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_2_text_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_2_text_pl',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AddField(
            model_name='page',
            name='footer_title_de',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='footer_title_en',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='footer_title_pl',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_title_de',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_title_en',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_title_pl',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_de',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_pl',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail_caption_de',
            field=models.CharField(blank=True, default='Thumbnail caption for this page', help_text='Thumbnail caption as displayed in Section Pages List. Can be left blank for Parent pages.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail_caption_en',
            field=models.CharField(blank=True, default='Thumbnail caption for this page', help_text='Thumbnail caption as displayed in Section Pages List. Can be left blank for Parent pages.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail_caption_pl',
            field=models.CharField(blank=True, default='Thumbnail caption for this page', help_text='Thumbnail caption as displayed in Section Pages List. Can be left blank for Parent pages.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_de',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_pl',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
    ]
