# Generated by Django 5.1.5 on 2025-04-05 13:54

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_page_button_1_text_de_page_button_1_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_de',
            field=models.TextField(blank=True, help_text='Address as displayed in header. Format text with break-lines', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.TextField(blank=True, help_text='Address as displayed in header. Format text with break-lines', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_footer_de',
            field=tinymce.models.HTMLField(blank=True, help_text='Address as displayed in footer. Format text with break-lines. For email link use mailto:email@g3.net.pl', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_footer_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Address as displayed in footer. Format text with break-lines. For email link use mailto:email@g3.net.pl', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_footer_pl',
            field=tinymce.models.HTMLField(blank=True, help_text='Address as displayed in footer. Format text with break-lines. For email link use mailto:email@g3.net.pl', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_pl',
            field=models.TextField(blank=True, help_text='Address as displayed in header. Format text with break-lines', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='button_form_text_de',
            field=models.CharField(blank=True, default='Contact in a traditional way', help_text='Button scrolls to header section contact info', max_length=60, null=True, verbose_name='Contact Form button'),
        ),
        migrations.AddField(
            model_name='contact',
            name='button_form_text_en',
            field=models.CharField(blank=True, default='Contact in a traditional way', help_text='Button scrolls to header section contact info', max_length=60, null=True, verbose_name='Contact Form button'),
        ),
        migrations.AddField(
            model_name='contact',
            name='button_form_text_pl',
            field=models.CharField(blank=True, default='Contact in a traditional way', help_text='Button scrolls to header section contact info', max_length=60, null=True, verbose_name='Contact Form button'),
        ),
        migrations.AddField(
            model_name='contact',
            name='fiscal_data_de',
            field=models.TextField(blank=True, help_text='VAT ID / REGON / KRS as displayed in header. Format text with break-lines', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='fiscal_data_en',
            field=models.TextField(blank=True, help_text='VAT ID / REGON / KRS as displayed in header. Format text with break-lines', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='fiscal_data_pl',
            field=models.TextField(blank=True, help_text='VAT ID / REGON / KRS as displayed in header. Format text with break-lines', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='footer_title_de',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='footer_title_en',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='footer_title_pl',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='form_header_de',
            field=models.CharField(blank=True, default='Drop us a line:', help_text='Max 80 characters.', max_length=80, null=True, verbose_name='Contact Form Header'),
        ),
        migrations.AddField(
            model_name='contact',
            name='form_header_en',
            field=models.CharField(blank=True, default='Drop us a line:', help_text='Max 80 characters.', max_length=80, null=True, verbose_name='Contact Form Header'),
        ),
        migrations.AddField(
            model_name='contact',
            name='form_header_pl',
            field=models.CharField(blank=True, default='Drop us a line:', help_text='Max 80 characters.', max_length=80, null=True, verbose_name='Contact Form Header'),
        ),
        migrations.AddField(
            model_name='contact',
            name='form_text_de',
            field=tinymce.models.HTMLField(blank=True, help_text='Format with break-lines.', null=True, verbose_name='Contact Form Text'),
        ),
        migrations.AddField(
            model_name='contact',
            name='form_text_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Format with break-lines.', null=True, verbose_name='Contact Form Text'),
        ),
        migrations.AddField(
            model_name='contact',
            name='form_text_pl',
            field=tinymce.models.HTMLField(blank=True, help_text='Format with break-lines.', null=True, verbose_name='Contact Form Text'),
        ),
        migrations.AddField(
            model_name='contact',
            name='menu_title_de',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='menu_title_en',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='menu_title_pl',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_title_de',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_title_pl',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_de',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_pl',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
    ]
