# Generated by Django 5.1.5 on 2025-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_contact_address_de_contact_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='link_text_de',
            field=models.CharField(blank=True, help_text='First link is displayed in the header as a button', max_length=60, null=True, verbose_name='Link text'),
        ),
        migrations.AddField(
            model_name='externallink',
            name='link_text_en',
            field=models.CharField(blank=True, help_text='First link is displayed in the header as a button', max_length=60, null=True, verbose_name='Link text'),
        ),
        migrations.AddField(
            model_name='externallink',
            name='link_text_pl',
            field=models.CharField(blank=True, help_text='First link is displayed in the header as a button', max_length=60, null=True, verbose_name='Link text'),
        ),
    ]
