# Generated by Django 5.1.5 on 2025-04-05 16:54

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_externallink_link_text_de_externallink_link_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='button_1_text_de',
            field=models.CharField(blank=True, help_text='Buttons 1 and 2 are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_1_text_en',
            field=models.CharField(blank=True, help_text='Buttons 1 and 2 are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_1_text_pl',
            field=models.CharField(blank=True, help_text='Buttons 1 and 2 are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 1 text'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_2_text_de',
            field=models.CharField(blank=True, help_text='Buttons 1 and 2 are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_2_text_en',
            field=models.CharField(blank=True, help_text='Buttons 1 and 2 are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_2_text_pl',
            field=models.CharField(blank=True, help_text='Buttons 1 and 2 are only displayed in Left and Right blocks', max_length=60, null=True, verbose_name='Button 2 text'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='header_de',
            field=models.CharField(help_text='Block header (required), max 80 characters.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='header_en',
            field=models.CharField(help_text='Block header (required), max 80 characters.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='header_pl',
            field=models.CharField(help_text='Block header (required), max 80 characters.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='text_de',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='text_pl',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='video_caption_de',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='video_caption_en',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='video_caption_pl',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='contentblockimage',
            name='caption_de',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='contentblockimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='contentblockimage',
            name='caption_pl',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='pagenotfound',
            name='link_text_de',
            field=models.CharField(blank=True, help_text='404 link text', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagenotfound',
            name='link_text_en',
            field=models.CharField(blank=True, help_text='404 link text', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagenotfound',
            name='link_text_pl',
            field=models.CharField(blank=True, help_text='404 link text', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagenotfound',
            name='text_de',
            field=models.CharField(blank=True, help_text='404 message text', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagenotfound',
            name='text_en',
            field=models.CharField(blank=True, help_text='404 message text', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagenotfound',
            name='text_pl',
            field=models.CharField(blank=True, help_text='404 message text', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='footer_title_de',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='footer_title_en',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='footer_title_pl',
            field=models.CharField(blank=True, help_text='Page title as displayed in footer (optional override of menu title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='menu_title_de',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='menu_title_en',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='menu_title_pl',
            field=models.CharField(help_text='Page title as displayed in page menu, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='meta_title_de',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='meta_title_pl',
            field=models.CharField(blank=True, help_text='Title displayed in browser tab and search results. This field overrides the default title generated from page title', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='text_de',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='text_pl',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_de',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_en',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_pl',
            field=models.TextField(help_text='Page title as displayed in page header, max 60 characters', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicybutton',
            name='button_text_de',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='privacypolicybutton',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='privacypolicybutton',
            name='button_text_pl',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Button text'),
        ),
    ]
