# Generated by Django 5.1.5 on 2025-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_contentblock_button_1_text_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='append_scroll_nav',
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='button_1_url',
            field=models.CharField(blank=True, help_text='Use relative paths for internal pages (e.g., /contact/). External links starting with "http" and scroll links starting with "#"', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='button_2_url',
            field=models.CharField(blank=True, help_text='Use relative paths for internal pages (e.g., /contact/). External links starting with "http" and scroll links starting with "#"', max_length=255, null=True, verbose_name='Button 2 URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_1_url',
            field=models.CharField(blank=True, help_text='Use relative paths for internal pages (e.g., /contact/). External links starting with "http" and scroll links starting with "#"', max_length=255, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_2_url',
            field=models.CharField(blank=True, help_text='Use relative paths for internal pages (e.g., /contact/). External links starting with "http" and scroll links starting with "#"', max_length=255, null=True, verbose_name='Button 2 URL'),
        ),
        migrations.AlterField(
            model_name='privacypolicybutton',
            name='button_url',
            field=models.CharField(blank=True, help_text='Use relative paths for internal pages (e.g., /contact/). External links starting with "http" and scroll links starting with "#"', max_length=255, null=True, verbose_name='Button URL'),
        ),
    ]
