# Generated by Django 5.1.5 on 2025-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_remove_contentblock_append_scroll_nav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='accept_button',
            field=models.CharField(blank=True, help_text='Cookies notification "Accept" button text', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='cookie_consent',
            field=models.TextField(blank=True, help_text='Cookies notification text', max_length=500, null=True, verbose_name='Cookies Consent Text'),
        ),
    ]
