# Generated by Django 5.1.5 on 2025-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_privacypolicy_accept_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='accept_button_de',
            field=models.CharField(blank=True, help_text='Cookies notification "Accept" button text', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='accept_button_en',
            field=models.CharField(blank=True, help_text='Cookies notification "Accept" button text', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='accept_button_pl',
            field=models.CharField(blank=True, help_text='Cookies notification "Accept" button text', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='cookie_consent_de',
            field=models.TextField(blank=True, help_text='Cookies notification text', max_length=500, null=True, verbose_name='Cookies Consent Text'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='cookie_consent_en',
            field=models.TextField(blank=True, help_text='Cookies notification text', max_length=500, null=True, verbose_name='Cookies Consent Text'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='cookie_consent_pl',
            field=models.TextField(blank=True, help_text='Cookies notification text', max_length=500, null=True, verbose_name='Cookies Consent Text'),
        ),
    ]
