# Generated by Django 5.1.5 on 2025-06-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_alter_contact_button_form_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='button_form_text',
            field=models.CharField(blank=True, default='', help_text='Button scrolls to header section contact info. Max 60 characters', max_length=60, null=True, verbose_name='Contact Form button'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='button_form_text_de',
            field=models.CharField(blank=True, default='', help_text='Button scrolls to header section contact info. Max 60 characters', max_length=60, null=True, verbose_name='Contact Form button'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='button_form_text_en',
            field=models.CharField(blank=True, default='', help_text='Button scrolls to header section contact info. Max 60 characters', max_length=60, null=True, verbose_name='Contact Form button'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='button_form_text_pl',
            field=models.CharField(blank=True, default='', help_text='Button scrolls to header section contact info. Max 60 characters', max_length=60, null=True, verbose_name='Contact Form button'),
        ),
    ]
