# Generated by Django 5.1.5 on 2025-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_alter_contact_button_form_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='meta_description_de',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='meta_description_pl',
            field=models.TextField(blank=True, help_text='Page description for search results (optional), max 255 characters', max_length=500, null=True),
        ),
    ]
