# Generated by Django 5.1.5 on 2025-03-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Max 60 characters', max_length=60, verbose_name='Name and surname')),
                ('role', models.CharField(blank=True, help_text='Expert role', max_length=60, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number in proper format', max_length=50, null=True)),
                ('email', models.CharField(blank=True, help_text='Email address in proper format', max_length=50, null=True)),
                ('header', models.TextField(blank=True, help_text='Call to action header. Format text with break-lines', max_length=60, null=True)),
                ('button_text', models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, help_text='Button URL. For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
            },
        ),
    ]
