# Generated by Django 5.1.5 on 2025-03-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='role',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines', max_length=60, null=True),
        ),
    ]
