# Generated by Django 5.1.5 on 2025-03-17 23:09

import experts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_alter_expert_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Expert thumbnail 1:1 ratio, 600px x 600px', null=True, upload_to=experts.models.upload_to),
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name and surname'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='role',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 60 characters', max_length=60, null=True),
        ),
    ]
