# Generated by Django 5.1.5 on 2025-03-18 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expert_thumbnail_alter_expert_name_alter_expert_role'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='label',
            field=models.ForeignKey(blank=True, help_text='Choose or create a new label. Labels are reusable accross the page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.label'),
        ),
    ]
