# Generated by Django 5.1.5 on 2025-03-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_expert_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='role',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
    ]
