# Generated by Django 5.1.5 on 2025-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_alter_expert_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='button_text_de',
            field=models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='expert',
            name='button_text_en',
            field=models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='expert',
            name='button_text_pl',
            field=models.CharField(blank=True, help_text='Button text', max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='expert',
            name='header_de',
            field=models.TextField(blank=True, help_text='Call to action header. Format text with break-lines', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='header_en',
            field=models.TextField(blank=True, help_text='Call to action header. Format text with break-lines', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='header_pl',
            field=models.TextField(blank=True, help_text='Call to action header. Format text with break-lines', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='role_de',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='role_en',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='role_pl',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
    ]
