# Generated by Django 5.1.5 on 2025-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expert_button_text_de_expert_button_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Expert Linkedin URL', max_length=50, null=True),
        ),
    ]
