# Generated by Django 5.1.5 on 2025-05-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0008_alter_expert_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='button_text',
            field=models.CharField(blank=True, help_text='Button text, max 60 characters', max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='button_text_de',
            field=models.CharField(blank=True, help_text='Button text, max 60 characters', max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='button_text_en',
            field=models.CharField(blank=True, help_text='Button text, max 60 characters', max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='button_text_pl',
            field=models.CharField(blank=True, help_text='Button text, max 60 characters', max_length=60, null=True, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='header',
            field=models.TextField(blank=True, help_text='Call to action header. Format text with break-lines, max 80 characters', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='header_de',
            field=models.TextField(blank=True, help_text='Call to action header. Format text with break-lines, max 80 characters', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='header_en',
            field=models.TextField(blank=True, help_text='Call to action header. Format text with break-lines, max 80 characters', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='header_pl',
            field=models.TextField(blank=True, help_text='Call to action header. Format text with break-lines, max 80 characters', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(help_text='Max 60 characters', max_length=60, verbose_name='Name and surname'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='role',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='role_de',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='role_en',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='role_pl',
            field=models.TextField(blank=True, help_text='Expert role. Format text with break-lines, max 120 characters', max_length=120, null=True),
        ),
    ]
