# Generated by Django 5.1.5 on 2025-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0009_alter_expert_button_text_alter_expert_button_text_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Expert Linkedin URL', max_length=100, null=True),
        ),
    ]
