# Generated by Django 5.1.5 on 2025-03-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_text', models.CharField(max_length=600, unique=True)),
                ('color', models.CharField(choices=[('light-grey', 'Light Grey'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('dark-yellow', 'Dark Yellow'), ('yellow', 'Yellow')], default='light-grey', max_length=20)),
            ],
        ),
    ]
