# Generated by Django 5.1.5 on 2025-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('light-grey', 'Light Grey'), ('grey', 'Grey'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('dark-yellow', 'Dark Yellow'), ('yellow', 'Yellow')], default='light-grey', max_length=20),
        ),
    ]
