# Generated by Django 5.1.5 on 2025-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_label_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='label_url',
            field=models.CharField(blank=True, help_text='(optional) URL for clickable labels (only on Case Study pages)', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_text',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
