# Generated by Django 5.1.5 on 2025-04-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_label_label_url_alter_label_label_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='label_text_de',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='label',
            name='label_text_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='label',
            name='label_text_pl',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
