# Generated by Django 5.1.5 on 2025-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_label_label_text_de_label_label_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_url',
            field=models.CharField(blank=True, help_text='(optional) URL for clickable labels (only on Case Study pages). Use relative paths for internal pages (e.g., /contact/). External links starting with "http" and scroll links starting with "#"', max_length=60, null=True),
        ),
    ]
