# Generated by Django 5.1.5 on 2025-05-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_alter_label_label_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_text',
            field=models.CharField(help_text='Max 60 characters', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_text_de',
            field=models.CharField(help_text='Max 60 characters', max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_text_en',
            field=models.CharField(help_text='Max 60 characters', max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_text_pl',
            field=models.CharField(help_text='Max 60 characters', max_length=60, null=True, unique=True),
        ),
    ]
