# Generated by Django 5.1.5 on 2025-03-06 17:26

import covers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_video', models.FileField(blank=True, help_text='mp4 file, recommended max size: 4Mb / length: ~30s. Upload either Video or Image Cover, not both.', null=True, upload_to=covers.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('cover_desktop', models.ImageField(blank=True, help_text='Horizontal, approximately 16:9 ratio, ratio 1920px wide', upload_to=covers.models.upload_to)),
                ('cover_laptop', models.ImageField(blank=True, help_text='Horizontal, approximately 16:9 ratio, 1680px wide', upload_to=covers.models.upload_to)),
                ('cover_tablet', models.ImageField(blank=True, help_text='Square or slightly vertical ratio, 1024px wide', upload_to=covers.models.upload_to)),
                ('cover_mobile', models.ImageField(blank=True, help_text='Square or slightly vertical ratio, 768px wide', upload_to=covers.models.upload_to)),
            ],
            options={
                'verbose_name': 'Cover',
                'verbose_name_plural': 'Covers',
            },
        ),
    ]
