# Generated by Django 5.1.5 on 2025-03-25 11:14

import covers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='cover_video',
            field=models.FileField(blank=True, help_text='WEBM / MP4 file, recommended max size: 4Mb / length: ~30s. Upload either Video or Image Cover, not both.', null=True, upload_to=covers.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
    ]
