# Generated by Django 5.1.5 on 2025-03-30 12:06

import covers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0002_alter_cover_cover_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_video', models.FileField(blank=True, help_text='WEBM / MP4 file, recommended max size: 4Mb / length: ~30s. Upload either Video or Image Cover, not both.', null=True, upload_to=covers.models.upload_to_cs, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])])),
                ('cover_desktop', models.ImageField(blank=True, help_text='Horizontal, approximately 16:9 ratio, ratio 1920px wide', upload_to=covers.models.upload_to_cs)),
                ('cover_laptop', models.ImageField(blank=True, help_text='Horizontal, approximately 16:9 ratio, 1680px wide', upload_to=covers.models.upload_to_cs)),
                ('cover_tablet', models.ImageField(blank=True, help_text='Square or slightly vertical ratio, 1024px wide', upload_to=covers.models.upload_to_cs)),
                ('cover_mobile', models.ImageField(blank=True, help_text='Square or slightly vertical ratio, 768px wide', upload_to=covers.models.upload_to_cs)),
            ],
            options={
                'verbose_name': 'Case Study Cover',
                'verbose_name_plural': 'Case Study Covers',
            },
        ),
    ]
