# Generated by Django 5.1.5 on 2025-03-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0003_casestudycover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name': 'Page Cover', 'verbose_name_plural': 'Page Covers'},
        ),
    ]
