# Generated by Django 5.1.5 on 2025-03-25 22:40

import django.db.models.deletion
import special_blocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=120, null=True)),
                ('svg_instructions', models.TextField(blank=True, help_text="Instructions for uploading SVG files. This text doesn't disaplay on page.", null=True, verbose_name='SVG Instructions')),
            ],
            options={
                'verbose_name': 'Clients',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_file', models.FileField(blank=True, help_text='Upload SVG file (preferably) or PNG if must be', null=True, upload_to=special_blocks.models.upload_to_clients)),
                ('order', models.PositiveIntegerField(default=0)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='special_blocks.clients')),
            ],
        ),
    ]
