# Generated by Django 5.1.5 on 2025-03-25 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogo',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='special_blocks.clients'),
        ),
    ]
