# Generated by Django 5.1.5 on 2025-03-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0002_alter_clientlogo_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='button_clients_text',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AddField(
            model_name='clients',
            name='button_clients_url',
            field=models.CharField(blank=True, help_text='For internal URL skip the language code. Start and end with a trailing slash "/"', max_length=255, null=True, verbose_name='Clients button URL'),
        ),
        migrations.AddField(
            model_name='clients',
            name='new_tab_clients',
            field=models.BooleanField(default=False, verbose_name='Open in new tab'),
        ),
    ]
