# Generated by Django 5.1.5 on 2025-03-26 22:21

import django.db.models.deletion
import special_blocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0003_clients_button_clients_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Founders',
                'verbose_name_plural': 'Founders',
            },
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Specialists',
                'verbose_name_plural': 'Specialists',
            },
        ),
        migrations.CreateModel(
            name='FounderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name and surname')),
                ('role', models.TextField(blank=True, help_text='Founder role. Format text with break-lines, max 60 characters', max_length=120, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Portrait, 1:1 ratio, 600px x 600px', null=True, upload_to=special_blocks.models.upload_to_founders)),
                ('order', models.PositiveIntegerField(default=0)),
                ('founders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='special_blocks.founders')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name and surname')),
                ('role', models.TextField(blank=True, help_text='Specialist role. Format text with break-lines, max 60 characters', max_length=120, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Portrait, 1:1 ratio, 600px x 600px', null=True, upload_to=special_blocks.models.upload_to_specialists)),
                ('order', models.PositiveIntegerField(default=0)),
                ('specialists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='special_blocks.specialists')),
            ],
        ),
    ]
