# Generated by Django 5.1.5 on 2025-03-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0004_founders_specialists_founderinfo_specialistinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientlogo',
            options={'ordering': ['order'], 'verbose_name': 'Logo', 'verbose_name_plural': 'Logos'},
        ),
        migrations.AlterModelOptions(
            name='founderinfo',
            options={'ordering': ['order'], 'verbose_name': 'Founder', 'verbose_name_plural': 'Founders'},
        ),
        migrations.AlterModelOptions(
            name='specialistinfo',
            options={'ordering': ['order'], 'verbose_name': 'Specialist', 'verbose_name_plural': 'Specialists'},
        ),
    ]
