# Generated by Django 5.1.5 on 2025-03-27 21:12

import django.db.models.deletion
import special_blocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_label_color'),
        ('special_blocks', '0005_alter_clientlogo_options_alter_founderinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Block header (required), max 80 characters.', max_length=80)),
                ('label', models.ForeignKey(blank=True, help_text='Choose or create a new label. Labels are reusable accross the page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.label')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
            },
        ),
        migrations.CreateModel(
            name='TimelineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='WEBP / JPG / PNG / GIF / ratio: 3:2 / width: 1280px (blocks Left, Right) / width: 1680px (block Full-width)', null=True, upload_to=special_blocks.models.upload_to_timeline)),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=240, null=True)),
                ('long_caption', models.TextField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(help_text='Year / date. End with colon ":", for example "2022:" or "Ferbruary 2025:"', max_length=30)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='special_blocks.timeline')),
            ],
            options={
                'verbose_name': 'Timeline Image',
                'verbose_name_plural': 'Timeline Images',
                'ordering': ['order'],
            },
        ),
    ]
