# Generated by Django 5.1.5 on 2025-03-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0006_timeline_timelineimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineimage',
            name='long_caption',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='year',
            field=models.CharField(blank=True, help_text='Year / date. End with colon ":", for example "2022:" or "Ferbruary 2025:"', max_length=30, null=True),
        ),
    ]
