# Generated by Django 5.1.5 on 2025-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0007_alter_timelineimage_long_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineimage',
            name='year',
            field=models.CharField(blank=True, help_text='Year / date, for example "2022" or "Ferbruary 2025"', max_length=30, null=True),
        ),
    ]
