# Generated by Django 5.1.5 on 2025-03-30 11:41

import special_blocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0008_alter_timelineimage_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogo',
            name='svg_file',
            field=models.FileField(default='/static/placeholder.jpg', help_text='Upload SVG file (preferably) or PNG if must be', upload_to=special_blocks.models.upload_to_clients),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='image',
            field=models.ImageField(default='/static/placeholder.jpg', help_text='WEBP / JPG / PNG / GIF / ratio: 3:2 / width: 1280px (blocks Left, Right) / width: 1680px (block Full-width)', upload_to=special_blocks.models.upload_to_timeline),
        ),
    ]
