# Generated by Django 5.1.5 on 2025-04-02 18:11

import special_blocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0010_alter_clientlogo_svg_file_alter_timelineimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineimage',
            name='image',
            field=models.ImageField(help_text='WEBP / JPG / PNG / GIF / ratio: 3:2 / width: 1500px', upload_to=special_blocks.models.upload_to_timeline),
        ),
    ]
