# Generated by Django 5.1.5 on 2025-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0011_alter_timelineimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='button_clients_text_de',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AddField(
            model_name='clients',
            name='button_clients_text_en',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AddField(
            model_name='clients',
            name='button_clients_text_pl',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AddField(
            model_name='clients',
            name='header_de',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='header_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='header_pl',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='role_de',
            field=models.TextField(blank=True, help_text='Founder role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='role_en',
            field=models.TextField(blank=True, help_text='Founder role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='role_pl',
            field=models.TextField(blank=True, help_text='Founder role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='founders',
            name='header_de',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='founders',
            name='header_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='founders',
            name='header_pl',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='specialistinfo',
            name='role_de',
            field=models.TextField(blank=True, help_text='Specialist role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='specialistinfo',
            name='role_en',
            field=models.TextField(blank=True, help_text='Specialist role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='specialistinfo',
            name='role_pl',
            field=models.TextField(blank=True, help_text='Specialist role. Format text with break-lines, max 60 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='specialists',
            name='header_de',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='specialists',
            name='header_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='specialists',
            name='header_pl',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='header_de',
            field=models.CharField(help_text='Block header (required), max 80 characters.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='header_en',
            field=models.CharField(help_text='Block header (required), max 80 characters.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='header_pl',
            field=models.CharField(help_text='Block header (required), max 80 characters.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='caption_de',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='caption_pl',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='long_caption_de',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='long_caption_en',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='long_caption_pl',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='year_de',
            field=models.CharField(blank=True, help_text='Year / date, for example "2022" or "Ferbruary 2025"', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='year_en',
            field=models.CharField(blank=True, help_text='Year / date, for example "2022" or "Ferbruary 2025"', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='timelineimage',
            name='year_pl',
            field=models.CharField(blank=True, help_text='Year / date, for example "2022" or "Ferbruary 2025"', max_length=30, null=True),
        ),
    ]
