# Generated by Django 5.1.5 on 2025-04-08 22:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0013_alter_founderinfo_role_alter_founderinfo_role_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founderinfo',
            name='role',
            field=tinymce.models.HTMLField(blank=True, help_text='Founder role. Format text with break-lines, max 60 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='founderinfo',
            name='role_de',
            field=tinymce.models.HTMLField(blank=True, help_text='Founder role. Format text with break-lines, max 60 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='founderinfo',
            name='role_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Founder role. Format text with break-lines, max 60 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='founderinfo',
            name='role_pl',
            field=tinymce.models.HTMLField(blank=True, help_text='Founder role. Format text with break-lines, max 60 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='role',
            field=tinymce.models.HTMLField(blank=True, help_text='Specialist role. Format text with break-lines, max 60 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='role_de',
            field=tinymce.models.HTMLField(blank=True, help_text='Specialist role. Format text with break-lines, max 60 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='role_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Specialist role. Format text with break-lines, max 60 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='role_pl',
            field=tinymce.models.HTMLField(blank=True, help_text='Specialist role. Format text with break-lines, max 60 characters', max_length=255, null=True),
        ),
    ]
