# Generated by Django 5.1.5 on 2025-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0014_alter_founderinfo_role_alter_founderinfo_role_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='button_clients_url',
            field=models.CharField(blank=True, help_text='Use relative paths for internal pages (e.g., /contact/). External links starting with "http" and scroll links starting with "#"', max_length=255, null=True, verbose_name='Clients button URL'),
        ),
    ]
