# Generated by Django 5.1.5 on 2025-05-07 19:53

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0015_alter_clients_button_clients_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='button_clients_text',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block, max 60 characters', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='button_clients_text_de',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block, max 60 characters', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='button_clients_text_en',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block, max 60 characters', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='button_clients_text_pl',
            field=models.CharField(blank=True, help_text='Fill-in if appending Clients list to this block, max 60 characters', max_length=60, null=True, verbose_name='Clients button text'),
        ),
        migrations.AlterField(
            model_name='founderinfo',
            name='name',
            field=models.CharField(help_text='Max 60 characters', max_length=60, verbose_name='Name and surname'),
        ),
        migrations.AlterField(
            model_name='founderinfo',
            name='role',
            field=tinymce.models.HTMLField(blank=True, help_text='Founder role. Format text with break-lines, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='founderinfo',
            name='role_de',
            field=tinymce.models.HTMLField(blank=True, help_text='Founder role. Format text with break-lines, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='founderinfo',
            name='role_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Founder role. Format text with break-lines, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='founderinfo',
            name='role_pl',
            field=tinymce.models.HTMLField(blank=True, help_text='Founder role. Format text with break-lines, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='founders',
            name='header',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='founders',
            name='header_de',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='founders',
            name='header_en',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='founders',
            name='header_pl',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='name',
            field=models.CharField(help_text='Max 60 characters', max_length=60, verbose_name='Name and surname'),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='role',
            field=tinymce.models.HTMLField(blank=True, help_text='Specialist role. Format text with break-lines, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='role_de',
            field=tinymce.models.HTMLField(blank=True, help_text='Specialist role. Format text with break-lines, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='role_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Specialist role. Format text with break-lines, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialistinfo',
            name='role_pl',
            field=tinymce.models.HTMLField(blank=True, help_text='Specialist role. Format text with break-lines, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='header',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='header_de',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='header_en',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='header_pl',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Max 240 characters', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='caption_de',
            field=models.CharField(blank=True, help_text='Max 240 characters', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='caption_en',
            field=models.CharField(blank=True, help_text='Max 240 characters', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='caption_pl',
            field=models.CharField(blank=True, help_text='Max 240 characters', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='long_caption',
            field=models.TextField(blank=True, help_text='Max 600 characters', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='long_caption_de',
            field=models.TextField(blank=True, help_text='Max 600 characters', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='long_caption_en',
            field=models.TextField(blank=True, help_text='Max 600 characters', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='timelineimage',
            name='long_caption_pl',
            field=models.TextField(blank=True, help_text='Max 600 characters', max_length=600, null=True),
        ),
    ]
