# Generated by Django 5.1.5 on 2025-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_blocks', '0016_alter_clients_button_clients_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='header',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='header_de',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='header_en',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='header_pl',
            field=models.CharField(blank=True, help_text='Max 120 characters', max_length=120, null=True),
        ),
    ]
